# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 37b441b9e2f78700ab92baf6d20c0262db1f77bd83724317ec0c1c117795db68f9d5fdfead0d62fa8cd53b5ca8a2e8b0add4d344fd3fc9f24db7c027ff77a49d

test:
  secret_key_base: 44392e85c608996db1e1d5f91de81febdf42483aeb7c640e701eaf40e838653d2fcad74459d1ab66cbb3206ffa6e25266a568ecbfcb25486c4c87ad0cd89e6aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
